### ISSUE TITLE
Advertisement 

### ISSUE THREAD

**Issue by kingfrostine66** [two-six/YT-Feeder#1]
Someone, I’m assuming the developer, thought it’d be a good idea to be a dick head and message me on discord offering a bribe if I starred their shit little project. Tried to message them back, but the pussy has everything set to private on discord so I’m leaving this here. Personally would not recommend using based on the developers sketchy behavior and offer of compensation. Fuck off and stop messaging random people.

**Comment by two-six** [comment]
I heard about this and informed moderators on this discord server to ban these people. I don't know these people and don't know why they advertise this project, if you get a dm,  please report them to the discord and to the server's moderators.

**Comment by kingfrostine66** [comment]
Hey man, sorry about the harsh language, thought it was you and I apologize for going off like that. What discord are you referring to? The only one I’m a member of that might fit is the unixporn discord.

**Comment by two-six** [comment]
No problem, I'm talking exactly about Unixporn Discord, I shared this project there about 21 hours ago and about 3 hours ago I've got a dm from someone asking me if I'm the one spreading these messages or is it just a bot. I've contacted Unixporn moderators and it seems they have banned this person, so maybe it will stop now.
Did you get similar messages from members of other Discord's servers?

**Comment by kingfrostine66** [comment]
No, I had only received one message, but by the time I had checked it, the user had no mutual servers with me. They offered nitro in exchange for starring the project here. I’m old, I don’t know what nitro is, and I can’t be bothered to star something. Although, after reading over this project, this is actually kind of neat and I might implement it. You might change my mind after all.
